name: flutter_hamburger_scaffold
description: Material Hamburger Scaffold Dedicated for flutter desktop applications
version: 0.0.1
author: Rafid Kotta <getrafid@gmail.com>
homepage: https://github.com/rafidkotta/flutter_hamburger_scaffold.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


